### ISSUE TITLE
CFNull error writing plist

### ISSUE THREAD

**Issue by sphen13** [munkireport/security#4]
output of manual run:
```
bash-3.2# /usr/local/munki/preflight.d/security.py 
Traceback (most recent call last):
  File "/usr/local/munki/preflight.d/security.py", line 387, in <module>
    main()
  File "/usr/local/munki/preflight.d/security.py", line 384, in main
    FoundationPlist.writePlist(result, output_plist)
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 122, in writePlist
    raise NSPropertyListSerializationException(error)
munkilib.FoundationPlist.NSPropertyListSerializationException: Property list invalid for format: 100 (property lists cannot contain objects of type 'CFNull')
```

the current "result" value to be written is:
```
{'gatekeeper': 'Active', 
'sip': 'Active', 
'firewall_state': '0', 
'firmwarepw': 'No', 
'ssh_groups': None, 
'ard_groups': 'All users permitted', 
'ard_users': 'All users permitted', 
'skel_state': 1, 
'ssh_users': 'All users permitted'}
```

**Comment by rickheil** [comment]
@sphen13 can you confirm what OS this is on?

**Comment by sphen13** [comment]
10.14.3 - was also happening on 10.13.6 @rickheil
